phases:
  pre_build:
    commands:
      - sudo ls /root
      - pip install -r requirements.txt
  build:
    commands:
      - python manage.py runserver
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - '**/*'
